### PR TITLE
Add jupyterlab starters

### PR DESCRIPTION
**Pull request by bollwyvl**
For #3.

This adds jupyter(lab)-starters. No doubt there will be some tire kicking here, hold on for a bumpy ride.

The behavior as it stands will be to copy the tutorials or examples to a folder (still called `robotkernel-examples|tutorials`) in the file browser. We can also pop a little form, defined in JSON schema, if we like. 

We can run (most) jupyterlab commands after the files get copied, but to get the ability to open a _particular_ file, either we would need to implement something importable in the `robotlab` package... thus far, the only example is for `cookiecutter`, and it's a bit... involved. Or (and!) I need to add that to the Jinja context, so one could simply ask for `{{ cwd }}/robotkernel-tutorial/00 JupyterLab User Interface.ipynb` in a JSON definition.

Other things:
- attic'ed `ride` (something's busted with `wx`), because we're not shipping it right now
  - also not testing `wx` importing in `pyshortcuts`
- bump lab version (i've tested it with other versions, but...)

### CODE REVIEW

**Comment by datakurre** [comment]
So exciting! I'll try this at the weekend at latest.

**Comment by bollwyvl** [comment]
Love it! Was up _way_ too long getting it working... to have it expect 8888, which was not easy to change. I guess I could cheat and change the notebook on disk, as the code mirror parts of rfjl aren't quite up to the task yet. For now I just commented it out. How often must one think about how testable the _authoring_ of their  documentation is?! 

I'll leave that remaining stuff commented out, as I don't want to create any more challenges if you're about to work on the content anyway.

So frankly, it's probably ready to look at, and merge if you are at all happy with it.

I can't guarantee that I'll get another release out this weekend (I predict :star: :gun: , :christmas_island: and :sleeping_bed:) that removes that One Last Click to actually launch the notebook we want. But there's a _lot_ of potential in the interplay between robot and starters.

On rfjl: I keep meaning to update it, but it's Close Enough, so 🤷. Maybe I owe us that, though, since we ship it.

I was also really hoping I'd have a language server story for you, but don't think it will be ready by january: while there's still a lot going on on the jplsp front, we haven't shipped in a while, and there are still some gnarly bits that prevent me from generally recommending it, despite our very brave beta users over there. The rf vscode robot language server hasn't been very responsive about publishing their stuff on npm, and I wouldn't event want to deal with potential node issues during a workshop anyway. rflsp has been deleted (which is fine, as it it was just a skeleton). Frankly, I think we know enough to really crank up what that could do for people, but it's Another Thing To Maintain and Test, and LSP has 124+ messages vs the 32 in JKMS... but maybe we should do it anyway, e.g. #55. I'll think about it.

**Comment by bollwyvl** [comment]
The notebook-based stuff is getting pretty good... The initial approach
uses nbconvert, but since it's already in the server, I'll probably make
them full kernels, and basically restart-run-all each time.

For our use case, it could launch a "guided" tutorial, and it would
successively build up the directory. You could even put in little quizzes,
e.g

 "in 00.ipynb, when does `Suite Setup` get run? Check all that apply.
 [ ] Every cell execution
 [ ] when it gets declared in Settings "

that don't let you proceed until you've mastered the content.

**Comment by datakurre** [comment]
@bollwyvl Unfortunately, I am unable to find the artifacts for this build at Azure Pipelines.

This URL https://dev.azure.com/robots-from-jupyter/robots-from-jupyter/_build/results?buildId=280&view=results does not show the usual Artifacts-menu for me. Is it just me or has something changed?

**Comment by datakurre** [comment]
Found it https://dev.azure.com/robots-from-jupyter/robots-from-jupyter/_build/results?buildId=280&view=artifacts&type=publishedArtifacts

**Comment by datakurre** [comment]
When starting a fresh Windows RobotLab installation, I get:

```
(base) C:\Users\user>python -m robotlab.labapp --browser=firefox
couldn't import cookiecutter: No module named 'cookiecutter'
```

Should be just add cookiecutter or should jupyter-starters to be silent on that when cookiecutter is not found?

Then a minor issue with the current starting experience:

Currently the first RobotLab launch starts with the SeleniumLibrary example. If I open launcher next to that notebook and click "RobotLab examples"-starter, it tries to create the examples into the current folder that is the actual original examples folder.

The above is a special case that jupyter-launcher should probably handle somehow, but should we change RobotLab to open launcher instead of the example notebook? Then I should create a new "Start here"-launcher that opens a single page tutorial.

I've been keeping the examples folder in robotkernel, because I had shared link there through nbviewer, but those link were before moving under robots-from-juputer. So, I should probably get rid of it and move everything under documentation. (Which should also be updated to prefer installation with RobotLab...)

**Comment by bollwyvl** [comment]
> Should be just add cookiecutter or should jupyter-starters 

Cookiecutter is very useful, but it does add a raft of dependencies (which i help package, but not maintain). It would definitely be appropriate for a developer-focused workshop, where after lunch you learned to package your first robot library, and don't want to monkey with `MANIFEST.in`.

> to be silent on that when cookiecutter is not found?

Silent is probably good.

> Currently the first RobotLab launch starts with the SeleniumLibrary example. If I open launcher next to that notebook and click "RobotLab examples"-starter, it tries to create the examples into the current folder that is the actual original examples folder.

Yeah, that's funny. So the simple starters don't get to know _where_ it's going to be installed, yet, so `foo/foo` is no different to it than `bar/foo`.

It's not actually the _original_ folder (the "gold master" is down in the conda env someplace). I'm open to whatever workflow makes sense... having the files already there vs. clicking a button to start. If we add a little form, and get the slow reveal, it will probably be a better experience to start empty.

> The above is a special case that jupyter-launcher should probably handle somehow, but should we change RobotLab to open launcher instead of the example notebook? Then I should create a new "Start here"-launcher that opens a single page tutorial.

Yeah, launching to the launcher probably makes sense to help orient people.

> I've been keeping the examples folder in robotkernel, because I had shared link there through nbviewer, but those link were before moving under robots-from-juputer. So, I should probably get rid of it and move everything under documentation. (Which should also be updated to prefer installation with RobotLab...)

I think it's fine to upsell RobotLab, but it's important that "the hard way" is still possible. Even the docs might make sense to be actually standalone (with a "production" binder that installs the real conda/pip/npm packages).

Anyhow: I'm trying real hard to get my stuff out the door to support the self-guided workflow backed by a notebook, but let me know if there's any quick win I can do to help out.

**Comment by datakurre** [comment]
Thanks! To summarize the discussion, for this pull, it would be enough if

* RobotLab would launch with the Launcher instead of the current example notebook
* if possible, jupyter-starters would be silent about missing cookiecutter

So, if you would be able to help a bit more, these would be the quick wins. For the workshop I don't need self-guided workflows, but I'd love to see an example when you are ready (any example, of course; no need to be robot related).

Let's not package cookiecutter. And I will prepare a new pull once I have updated starter and tutorial notebooks. For this iteration they will still live in robotkernel. I'm kind of already waiting for the discussions at RoboCon before making too big decisions :-)

**Comment by bollwyvl** [comment]
on it.

**Comment by bollwyvl** [comment]
> RobotLab would launch with the Launcher instead of the current example notebook 

I just ran a clean setup: i think this is because you might have been looking at the example, and it's stored in a workspace in your home directory. Try deleting/moving your `~/.jupyter` directory and launching robotlab, and it should go to the launcher. 

We could also consider creating our own preferences and workspace directories, i suppose...

**Comment by bollwyvl** [comment]
> RobotLab would launch with the Launcher instead of the current example notebook

Yeah, just ran a full thing of this again, and if you've never launched lab before, you get the launcher.

> if possible, jupyter-starters would be silent about missing cookiecutter

Fixed!

**Comment by bollwyvl** [comment]
Obviously no pressure to add/do anything! It's already been really helpful
to have good use cases from here for starters.

Another thing that's relatively quick (on the robotlab side) is to provide
a Schema that pops a form where you put in the name of the directory that
you want (with a default)... But right now, the commands are not
parametrized, so it would still just open the folder, and you'd manually
open the 00.ipynb. still tinkering to make simple things simple with json!

the notebook one is already pretty nuts, [Binder](https://mybinder.org/v2/gh/bollwyvl/jupyterlab-starters/add-notebook-as-starter?urlpath=lab%2Ftree
) works, getting close to being really useful for lots of things. It starts
to get a little crazy, as it's non-trivial to edit a schema itself with
react-jsonschema-form, but having things like jupyterlab command discovery
in the form are pretty cool.

And I _still_ think that documentation librarian is a good idea... But I'll
be seeing the starter stuff through, first!

Also, blockly has recently been getting a lot more sane to integrate. I
haven't picked that up since the summer, but once their next release drops,
I'll be having a serious look.

We're also ramping up the robot testing on the notebook side of jlsp...
Again, no chance it would be ready by robocon, but certainly getting there.
In doing that work, and encountering the limitations of the existing
node-based language server, even in vscode, I think we will in fact want to
do a robots-from-jupyter/robotframe-languageserver. It's implementation
would further highlight the parts of rk that could either be proposed to
core, or moved into a separate package that rk and rfls could both use. I
think between --dryrun, rflint, and the discovery, completion, string
loading, etc. machinery we've built, we could offer some really good value.

**Comment by datakurre** [comment]
@bollwyvl Thanks again!

I'm sorry for that wrong positive about RobotLab opening an example on the first run. I just did uninstall + install and completely forgot about the persisting .jupyter-directories. I do have a snapshot of virtual machine before any RobotLab installs, so I will now remember to revert to that snapshot before filing similar issues in the future...

I also tried to use the existing RF vscode language server outside vscode, and did not get very far with it.

JupyterLab offers too much cool possibilities... :-)

**Comment by bollwyvl** [comment]
Still raises the question of whether we should have separate
workspace/settings dirs... it's probably a two-line fix. But then, even had
we done that, it would persist between re-installs :(

**Comment by datakurre** [comment]
@bollwyvl I tested Window build and merged. Thanks a lot and have awesome holidays once you get there!

I'll ping you for comments once I have something to show for updated tutorials and starters. I keep getting side tracked with some almost completely unrelated nix stuff (very comparable to you having to tweak conda stuff for robotlab :)

**Comment by bollwyvl** [comment]
brave man! Woo! And now i have a downstream :P

But I've pinned for the 0.1.x line, so none of the freaky stuff I'm working
on should break on you.

**Comment by bollwyvl** [comment]
Ah, the joys of packaging stuff well enough to be shippable!

**Comment by bollwyvl** [comment]
Just an update: the kernel-backed starter thing is released in the 0.2.0
line, up on pypi and npm. When you've got some updated content (no rush)
I'd love to experiment with an rk starter notebook to run through the
tutorial... Most of it would be stuff from operatingsystem, collections and
builtin, with a few helpers for manipulating notebook metadata. No doubt
I'll discover more stuff we want!

I'll also be using it at $DAY_JOB, so who knows what kinda bells and
whistles I'll need.

**Comment by datakurre** [comment]
Thanks for the update! You could expect updates next weekend. 🤞I have started updating the material, but not completed.

https://mybinder.org/v2/gh/robots-from-jupyter/robotkernel/docs?urlpath=lab already has starters enabled, I believe.

**Comment by bollwyvl** [comment]
Neat!

**Comment by bollwyvl** [comment]
Ha tried the binder and you're already pulling in the 0.2.0 stuff. Fearless!

The big focus was on trying to make it a little more sane to work with
things like the initial schema and the svg, which are kind of a beast to
write in an etc file. The toolbar now lets you hack everything that will
show up in the launcher, such that you only need the minimum information in
the config file.

In a schema form, one can also now use markdown (and mathjax lol) in titles
and descriptions to make stuff pretty. I stopped just short of putting full
outputs in there, as there's a lot of open questions in my mind about how
useful they would be without access to the running kernel, where to put it
on the screen, etc.

**Comment by datakurre** [comment]
@bollwyvl I still don’t see the full possibilities of starters, so I will only use it to create ”dummy” launcher buttons for notebooks and folders, but will learn about your examples later :)

**Comment by bollwyvl** [comment]
Right, because no docs! Something's gotta give, and tests were more
important to keeping me sane. But simple is good! I did note you've got a
mix of the 0.1.0 backend and the 0.2.0 frontend, which I hadn't tested...
But it appears to work for "copy". Ha! Anyhow, the starters binder has an
example notebook that just keeps making more (text) files, but the approach
should really shine with episodic content.

**Comment by datakurre** [comment]
Ok. Finally learned through Starter Notebook and Multi-Stage Starter Notebook... and I am speechless. I doubt I have time to use that method for workshop, but will take that to RoboCon sprints. That could make awesome demo after sprinting a day.

**Pull request merged**
