### PR TITLE
Release 1.0rc1

### PR DESCRIPTION
**Pull request by datakurre**
- [x] update hashes for robotkernel 
  - [x] sdist
  - [x] gh source for examples
- [ ] check versions and noarch of repackaged/new upstreams
  - [ ] revisit chromedriver
- [ ] tag
- [ ] upload builds to gh
- [ ] blog post

### CODE REVIEW

**Comment by bollwyvl** [comment]
Still tinkering locally with this...

In other news, given that the browsers are starting to get more aggressive
on the pop-up script injection, it might be important to do the log/report
viewer sooner rather than later.

**Comment by datakurre** [comment]
@bollwyvl Would you be able to give my account "atsoukka@jyu.fi" at Azure DevOps enough permissions to download test artifacts?

**Comment by datakurre** [comment]
Curious that every platform has different set of chrome and chromedriver versions. Other seems to be ok, but for Windows the combination is not officially supported:

```
  (Session info: headless chrome=71.0.3578.98)
  (Driver info: chromedriver=2.41.578737 (49da6702b16031c40d63e5618de03a32ff6c197e),platform=Windows NT 10.0.14393 x86_64)
```

According to http://chromedriver.chromium.org/downloads version 2.43 is the first one to officially support chrome 71.

**Comment by bollwyvl** [comment]
> Curious that every platform has different set of chrome and chromedriver versions. Other seems to be ok, but for Windows the combination is not officially supported:

Good for testing, I guess? :stuck_out_tongue_closed_eyes: 

Having a look now locally...

**Comment by bollwyvl** [comment]
Ugh, the chromedriver situation is not fantastic. I think we'll probably need to build, and potentially distribute, a number of versions, if only to be able to test this properly. Sigh.

**Comment by datakurre** [comment]
Well, there was also some firefox error in the logs.

Anyway, sad that this race between browser and driver versions still continue.

**Comment by datakurre** [comment]
I'm sorry to not be able to test this locally myself. NixOS has working package for miniconda, but it cannot work around binary packages like chromedriver expecting shared libraries outside conda.

Would you happen to have suitable vagrant setup around? Of course, that would only help testing Linux.

**Comment by datakurre** [comment]
Any chance that those chrome errors are just regular selenium timing issues? Something is being done too fast and some code in JupyterLab raises alert dialog? (To avoid user missing changes due to browser location change.)

**Comment by datakurre** [comment]
Access to those test artifacts could give also me some chance to fix this :)

**Comment by datakurre** [comment]
MacOS tests did pass once, so I vote for timing issues.

**Comment by bollwyvl** [comment]
> Would you happen to have suitable vagrant setup around? Of course, that would only help testing Linux.

Vagrant _can_ help, but I am not real big on maintaining Yet Another Build Chain. Locally, I use vbox directly for windows, but encapsulating with vagrant has never given me very good results for that target. And OSX, well...

> Access to those test artifacts could give also me some chance to fix this :)

Hm I don't think there are many bits to twiddle: can you get at the _RobotLab Robot Output_ from:

https://dev.azure.com/robots-from-jupyter/robots-from-jupyter/_build/results?buildId=58&view=results

I can hit them from an an un-logged-in browser.

**Comment by bollwyvl** [comment]
> Any chance that those chrome errors are just regular selenium timing issues?

It's all possible, but we don't want to ship a machine with drivers that won't be useful for people's increasingly evergreen browsers...

**Comment by datakurre** [comment]
@bollwyvl Yes, I can get "RobotLab Robot Output". I didn't realize that it was the on containing test reports and was trying to download only the platform specific ones that gave me permission error.

Thanks! I look into those later (maybe tomorrow) and try to fix the build.

If you could look into having up-to-date chromedriver (that is ChromeDriver 2.46 I guess) for every platform, that would be great!

**Comment by bollwyvl** [comment]
> ChromeDriver 2.46 I guess

The situation is now [totally crazy](http://chromedriver.chromium.org/downloads):

| chrome | 2.45 | 2.46 | 72.0.3626.69  | 73.0.3683.68 | 74.0.3729.6 |
|--------|------|------|---------------|--------------|-------------|
| 74     |      |      |               |              | x           |
| 73     |      | x    |               | x            |             |
| 72     | x    | x    | x             |              |             |
| 71     | x    | x    |               |              |             |
| 70     | x    |      |               |              |             |

So yeah, we should ship 2.46, but it seems like we should _already_ be shipping 73 and 74

**Comment by bollwyvl** [comment]
Hooray, one green checkmark!

**Comment by bollwyvl** [comment]
~~And indeed, OSX for free (i mean, i didn't look have to look at it). Will check out for windows locally and see what i can see...~~

Totally misread that! Could be a bit more of a slog to get to the bottom of OSX...

**Comment by datakurre** [comment]
I agree that Chromedriver situation is crazy, but the docs imply that for "development versions" 2.46 is still the best guess, so probably it mostly works for all new versions. Alternatively, if Conda distributes Chromium, should we add some extra weight and ship with that and matching Chromedriver versions?

I'm spoiled by NixOS shipping keeping Chrome and Chromedriver in sync for me.

**Comment by datakurre** [comment]
<strike>Windows builds give error only for Firefox. How to check that we have Firefox there? </strike> (Too fast. Firefox passes on other tests than the failing one. Still investigating.)

**Comment by datakurre** [comment]
I still don't have local dev environment, so I'm trying out things here directly while travelling. Remain patient :)

**Comment by datakurre** [comment]
I'll now squash all these into a new pull (to not break your history).

**Comment by datakurre** [comment]
To be continued at https://github.com/robots-from-jupyter/robotlab/pull/29

**Pull request closed without merging**
