### PR TITLE
[wip] Prepare for 2019.12.x

### PR DESCRIPTION
**Pull request by bollwyvl**
just starts rolling some versions for #57.

Locally stuff dying during acceptance tests, as no doubt you would expect (I haven't looked into the API changes):

```
+ nbrobot --help
Traceback (most recent call last):
  File "/tmp/tmppdteo8j0RobotLab/bin/nbrobot", line 6, in <module>
    from robotkernel.nbreader import robot
  File "/tmp/tmppdteo8j0RobotLab/lib/python3.6/site-packages/robotkernel/nbreader.py", line 7, in <module>
    from robot.parsing import populators
ImportError: cannot import name 'populators'
```

But hey, stuff is building! Let's see what CI turns up that I don't expect...

### CODE REVIEW

**Comment by datakurre** [comment]
Yes, RF 3.2 requires changes for robotkernel (the old parser in RF is no more) and I’m only half-way there.

**Comment by bollwyvl** [comment]
no worries. just doing what chores i can :P

**Comment by bollwyvl** [comment]
Oooh, new deprecations:
```
[ WARN ] Accessing variable items using '&{FIREFOX}[${OS}]' syntax is deprecated. Use '${FIREFOX}[${OS}]' instead.
```

**Comment by datakurre** [comment]
I got a second thought about RF 3.2a1. I have updated robotkernel to support 3.2a1, but it's better to still make 2019.12 release with robotframework 3.1.2. I split this into

* https://github.com/robots-from-jupyter/robotlab/pull/59
* https://github.com/robots-from-jupyter/robotlab/pull/60

**Pull request closed without merging**
