### PR TITLE
Pin pywinpty >=0.5.5 to fix #54

### LINKED ISSUE #54: Unable to create new "Terminal" session on Windows
Steps

1. install RobotLab on Windows
2. start RobotLab
3. File => New => Terminal

Expected

Terminal session opens

What actually happens

Terminal session opens and closes so fast that I'm unable to see what happens.

RobotLab launch terminal printed the following

```
[I 23:18:00.308 LabApp] EOF on FD 2688; stopping reading
[I 23:18:00.526 LabApp] Terminal 1 closed
TermSocket.open: 1
[I 23:18:00.526 LabApp] New terminal with specified name: 1
TermSocket.open: Opened 1
Exception in thread Thread-16:
Traceback (most recent call last):
  File "C:\Users\user\RobotLab\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Users\user\RobotLab\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\user\RobotLab\lib\site-packages\winpty\ptyprocess.py", line 331
, in _read_in_thread
    data = pty.read(4096)
  File "C:\Users\user\RobotLab\lib\site-packages\winpty\winpty_wrapper.py", line
 73, in read
    ReadFile(self.conout_pipe, data, length, None, None)
OSError: exception: access violation writing 0x0000000000000000

[I 23:18:00.761 LabApp] EOF on FD 2680; stopping reading
[I 23:18:00.980 LabApp] Terminal 1 closed
```

### PR DESCRIPTION
**Pull request by datakurre**
Just guessing, if this is the right way to fix. [fixes #54]

### CODE REVIEW

**Comment by datakurre** [comment]
So, I guessed wrong. Added one version pin and got conflicts for all of them.

**Comment by bollwyvl** [comment]
Conda has lots of "hidden" defaults so that stuff mostly just works on windows. Constructor does not inherit all of them, and requires you be much more specific. Hopefully this helps: it did allow me to solve some of our nastiest stuff locally:

```bash
#!/usr/bin/env bash
export CONDA_SUBDIR=win-64

conda create \
  --dry-run \
  -p win-foo \
  -c https://conda.anaconda.org/anaconda \
  -c https://conda.anaconda.org/conda-forge \
  -c https://conda.anaconda.org/msys2 \
  'pywinpty>=0.5.5' \
  'python=3.6' \
  'pythonnet' \
  'pillow' \
  'pyqt' \
  'opencv'

```

**Comment by bollwyvl** [comment]
[groovy](https://dev.azure.com/robots-from-jupyter/robots-from-jupyter/_build/results?buildId=253&view=logs&jobId=d055f5c4-e279-55b9-5032-0d33e0eac1d6&taskId=ef23cb43-7956-54f4-b6c1-0a42cd89300b&lineStart=116&lineEnd=117&colStart=1&colEnd=1)

**Comment by bollwyvl** [comment]
unfortunately, i have no idea how to test this, short of busting out the opencv to OCR for errors...

**Comment by bollwyvl** [comment]
I think that's a normal flake... will try a little CI bait...

**Comment by bollwyvl** [comment]
:moneybag:

**Comment by datakurre** [comment]
I try the installer from this build later today.

**Comment by datakurre** [comment]
Works for me!

**Comment by bollwyvl** [comment]
Hooray! It's pretty bad the days when it's actually a conda problem, and
not a data (e.g channels, specs,) problem... We'd have needed msys2 anyway
when adding more gnu tool (e.g. git). Do you think we should make white
depend on that pywinpty, or do I just not really want to know?

**Comment by datakurre** [comment]
Nicholas Bollweg wrote:
> Hooray! It's pretty bad the days when it's actually a conda problem, and
> not a data (e.g channels, specs,) problem... We'd have needed msys2 anyway
> when adding more gnu tool (e.g. git). Do you think we should make white
> depend on that pywinpty, or do I just not really want to know?

How was this connected to white? 🤔

**Comment by bollwyvl** [comment]
I thought this was triggered by white needing pythonnet...

**Comment by datakurre** [comment]
Oh. sorry about that. My fault of mixing two issues into one.

White was fixed with up-to-date Windows.

pywinpty pin was needed to fix JupyterLab Terminal feature on Windows. It is already a dependency, but the shipped version was broken.

**Pull request merged**
