### PR TITLE
[wip] Build robotframework-whitelibrary

### PR DESCRIPTION
**Pull request by bollwyvl**
c/f #29 and #27

I wouldn't block those, but I'd like to at least give this a shot before _I_ would pull the trigger. @datakurre if you've got a deadline, though, be my guest!

This tries doing a rather heavy build (`pythonnet`, might take some time), but gives up on building `robotframework-whitelibrary` (uses nuget, rebundles, etc.) in advance. :crossed_fingers: 

Rationale: Ideally, we wouldn't have anything blocking/error-producing as a side-effect of a broken post-install script (I literally have nightmares about them... and windows in general). Doing binary-adjacent `pip` installs is a _great_ way to get a broken env, and ours isn't exactly simple...

### CODE REVIEW

**Comment by bollwyvl** [comment]
Had to re-target this at `master` to get CI to start... hm...

**Comment by datakurre** [comment]
Of course, I want to see this. I also would like to get rid of explicit Sleeps in acceptance test suites.

I'll merge the release-pull into master without release and create separate ticket for that.

**Comment by datakurre** [comment]
```
This version of ChromeDriver only supports Chrome version 74
  (Driver info: chromedriver=74.0.3729.6 (255758eccf3d244491b8a1317aa76e1ce10d57e9-refs/branch-heads/3729@{#29}),platform=Linux 4.15.0-1037-azure x86_64
```

**Comment by datakurre** [comment]
https://anaconda.org/conda-forge/python-chromedriver-binary

Last upload: 4 hours and 48 minutes ago

**Comment by datakurre** [comment]
I seem to be unable to get the "wheelhouse" path passed to pip so that it would accept it.

**Comment by datakurre** [comment]
@bollwyvl I was left puzzled by this approach. pip expects archives at --find-links, but conda unpacks them and therefore pip does not find the package nor tries to build it.

**Comment by bollwyvl** [comment]
Oooh, i didn't think it would expand wheels. That's gross. Should be a relatively quick fix. Sorry for all the trouble!

**Comment by datakurre** [comment]
Not wheels, but you had added whitelibrary with tar.gz extension so I assumed you wanted to try source distribution for it. I didn’t try with wheel for that yet...

**Comment by bollwyvl** [comment]
Having a go at actually packaging rfwl: works locally (on a win vm).

Looking at what's in the actual wheel, it might be appropriate to actually split out the bundled binaries into their own packages.

**Comment by datakurre** [comment]
Awesome! I'll try out the resulting Windows installer later today.

**Comment by bollwyvl** [comment]
Hey, cool, all green!

**Comment by datakurre** [comment]
I’ll merge and we see if MacOS build still flickers.

I tried the windows installer yesterday and it seemed to work for me.

**Pull request merged**
