### PR TITLE
Build More Robots

### PR DESCRIPTION
**Pull request by bollwyvl**
This starts experimenting with some ideas from #42.

### CODE REVIEW

**Comment by bollwyvl** [comment]
That is a whole bunch of jobs. Funny thing is, it _shouldn't_ take any longer than what we were doing before.

**Comment by datakurre** [comment]
🙈👍🚀👌

**Comment by bollwyvl** [comment]
it looks like we have a viable approach here. it's nice that it isn't taking an appreciable amount of extra time to do 6 additional installers/tests, which validates keeping it all in the same place.

It should be fairly easy to add just about any other custom spins we would want, and of course we'd want to do more testing of the things we ship... no need to test robot, as each of them is already doing _that_ for the most part, but no doubt there are some things worth checking to make sure they are working.

Anyhow, it's not my coal or hard disks, so I'd say we can go ahead and just start doing this, pending any other packages we should be building/including, or any other review.

**Comment by datakurre** [comment]
Just awesome. I'll find a time to give those Windows builds a spin... 

Probably needs some documentation later about where to find and how to run the binaries / scripts, but RIDE did run fine on Windows.

**Comment by bollwyvl** [comment]
> Probably needs some documentation later about where to find and how to run the binaries 

There are some built-in capabilities for this on [windows in conda-build](https://docs.conda.io/projects/conda-build/en/latest/resources/add-win-start-menu-items.html) that i can explore... but indeed, we'd need some documentation for each of these.

**Comment by bollwyvl** [comment]
All those builds, not getting built now! Give me an emoji, and I'll merge.

I also added a `buildId` to all of the outputs, for ease of downloading, which seemed convenient. But then it goes and works the first time, so i didn't have to download them and/or clean out any old ones.

I did do some drawing: nothing super solid to show for it. There's not much you can do with a feature table, and there's certainly bounded complexity to how much you can stuff in there. There are a few hierarchies that came to mind, but i think one of the more logical ones was...

  - get: download buttons labelled with file size (maybe make it sticky as you scroll)
  - setup: estimate of install time (it's pretty real on windows) and space on disk
  - learn: what docs you'll get to help you (`man`/libdoc/inspector/lsp/...)
  - system-under-test: what you can test (py/cli/web/wx/white/vms)
  - use: what UIs you can use to build stuff (tty/ipython/lab/ride)
  - automate: how you can use it in a pipeline (azure ain't easy, travis is dying... maybe actions once out of beta?)
  - analyze: how to use many test reports for trends (html/xml/pandas/tcms)
  - upgrade: how you will be able to get new stuff (pip/jlpm/conda)
  - remove: `rm -rf` vs `click-and-uninstall`

A funny thing that came to mind, sort of related to the Hub concept, is a "Pro" spin (think a second, full day workshop), which includes the things you would need to extract, build, test, and package new robot libraries (or extensions to kernel) as part/in support of a team. On the backend, you'd have your tooling like `git`, while on the front-end, I'd stuff in [jupyterlab-git](https://github.com/jupyterlab/jupyterlab-git). Ship `pytest`, `robotframework-statuschecker`, `robotframework-lint`, `black`, etc. Ship `conda-build`, and maybe even `constructor` (since we can't ship nix :stuck_out_tongue_winking_eye: ). Anyhow :pizza: for thought.

**Comment by datakurre** [comment]
All this sounds great as usual! I have more time to thing all this starting from November, when I start updating workshop materials. So many possibilities that hard to know where to focus with limited time without much real user feedback :/

**Comment by bollwyvl** [comment]
Yeah, have been trying to get some folks excited about a local workshop in
house... It would be good to get some more feedback!

**Pull request merged**
