### PR TITLE
Prepare for 2019.12.0

### PR DESCRIPTION
**Pull request by datakurre**

### CODE REVIEW

**Comment by bollwyvl** [comment]
Go go go! How can I help?

**Comment by datakurre** [comment]
@bollwyvl I probably need help with that test failure in testing robotframework release and then in the release process.

But I will look into the failure later on Thursday evening.

**Comment by datakurre** [comment]
We probably should try applying this before tests https://github.com/robotframework/robotframework/commit/70af9e3bab0217b0450d78c69e6c2ccb8f9c342d

**Comment by datakurre** [comment]
@bollwyvl Green! Help in drafting the release would be awesome!

**Comment by bollwyvl** [comment]
Looking good!

> Help in drafting the release would be awesome!

What are you looking for? It doesn't seem like a bunch of narrative is required, as we'll hopefully end up pushing out something with some more final revs...

**Comment by datakurre** [comment]
I guess these are the major changes between 2019.9.0 and 2019.12.0

- robotkernel = 1.2
- robotframework-seleniumlibrary = 4.1.0
- jupyterlab = 1.2.3
- @jupyter-widgets/jupyter-labmanager = 1.1.0   

- jupytext = 1.3.0
- robotframework-seleniumtestability = 0.0.15

In addition, 2019.12.0 is compatible with RF 3.2a1 when manually upgraded after installation.

**Comment by datakurre** [comment]
Slightly related. OpenCV example for robotkernel fails currently at Binder, because of
```
import cv2

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-2-c8ec22b3e787> in <module>
----> 1 import cv2

ImportError: libGL.so.1: cannot open shared object file: No such file or directory
```

I recall it has been working. Does that need something extra in Binder configuration nowadays?

https://github.com/robots-from-jupyter/robotkernel/tree/master/binder

**Comment by datakurre** [comment]
This should now be ready for merge.

**Comment by bollwyvl** [comment]
Ooh I should looks into the opencv thing... But merge if you're happy with
it otherwise!

**Comment by datakurre** [comment]
@bollwyvl So what is really required to turn this into a release? 🤔 I could follow the steps we listed previously manually with the latest builds from this pull, but I assume that you already automated some parts of it? 

I’d love to have a release that I would use myself to update the training materials for my RoboCon workshop. Then I’d have 100 % confidence on everything at the workshop. 🙏

**Comment by bollwyvl** [comment]
I'll try making a tag, and see what happens!

**Comment by bollwyvl** [comment]
https://dev.azure.com/robots-from-jupyter/robots-from-jupyter/_build/results?buildId=270

**Comment by bollwyvl** [comment]
I got rid of your previous draft (whoops): I don't know why it didn't start the tag build, but assume it would create a problem if it got all the way to the release stage and there was already something there. We should get some installers submitted as a draft, and then we just need to monkey with the release text.

Of course, we haven't tested this in some time, so who knows...

**Comment by bollwyvl** [comment]
well, it got to the release stage!

**Comment by bollwyvl** [comment]
and it's uploading...

**Comment by bollwyvl** [comment]
and they're in there! ...but with a janky auto-generated release message...

**Comment by datakurre** [comment]
@bollwyvl Thanks! So everything is automated, but somehow my tag didn’t trigger that.

I’ll try out the builds in following days!

**Comment by datakurre** [comment]
* [x] Windows
* [x] Linux
* [x] MacOS

**Comment by datakurre** [comment]
All tested and looks good.  Did you have any scripts to help with the release notes previously?

**Comment by bollwyvl** [comment]
> So everything is automated, but somehow my tag didn’t trigger that.

I don't think draft tags made through the web ui get picked up by azure. I did a CLI `git tag` and `git push --tags` and it worked without any other interaction.

>  Did you have any scripts to help with the release notes previously?

nope, did it by hand. I guess we'd just copy paste, and maybe grab the listing from CI while its still available. It would be nice to do better, of course!

**Comment by bollwyvl** [comment]
mostly updated...

**Comment by datakurre** [comment]
Looking good.  I added jupytext into new packages.

**Comment by bollwyvl** [comment]
Ahh, good catch.

**Comment by datakurre** [comment]
@bollwyvl Found an issue. Jupytext Lab extensions is not available.

I had to install it manually with `!jupyter labextension install jupyterlab-jupytext` from Python notebook to make it available.

We should add that into build, but what would be proper way to install new extensions on top of RobotLab install? What is the proper way to activate the env from Window Cmd prompt? Or maybe "Terminal" from Jupyter Lab, but returned NPM error, because it could not find "node.exe" from path :thinking:

**Comment by datakurre** [comment]
Fixed jupyterlab-jupytext. Removed draft (after taking backup of notes). Pushed moved tag. Now waiting for the magic to happen.

**Comment by datakurre** [comment]
Almost. Help still required for testing Linux installer.

* Windows installer ok
* OSX installer ok
* Linux seems corrupted for me (fails to unpack files after license questions)

**Comment by bollwyvl** [comment]
Does the Sha match the calculated hash? That would be annoying if we
couldn't rely on the pipeline to release the binaries we had actually
tested...

**Comment by bollwyvl** [comment]
Hm, just downloaded and ran without issue on Ubuntu 19.10. Heck, even the deskop icon worked (had to right click and say `Allow Launching`, but I'll take it). SHA sums matched up, so I'm pretty sure i tested what CI was putting down.

```
$> ~/Downloads$ sha256sum RobotLab-2019.12.0-Linux-x86_64.sh 
40dc50fe9d2a6604d39a48a6b63c9b96442e8087c65f58c4614e68fc44e192e9  RobotLab-2019.12.0-Linux-x86_64.sh
$> ~/Downloads$ more SHA256SUMS 
40dc50fe9d2a6604d39a48a6b63c9b96442e8087c65f58c4614e68fc44e192e9  RobotLab-2019.12.0-Linux-x86_64.sh
73ec3fbf60de2b5bc2158f5c32ae8cd7a9da07fcbdebde361f88893be5d490a4  RobotLab-2019.12.0-MacOSX-x86_64.sh
18183b31430d00cd30e639f5d8245e134a54c43ec9c28eea7acc65f924dd8cae  RobotLab-2019.12.0-Windows-x86_64.exe
$> ~/Downloads$ bash RobotLab-2019.12.0-Linux-x86_64.sh -fbp /tmp/robotlab-2019.12.0
PREFIX=/tmp/robotlab-2019.12.0
...
Preparing transaction: done
Executing transaction: done
Making RobotLab shortcut in $HOME...
 ~
Shortcut created...
{'args': '',
 'description': 'Launch RobotLab in Firefox in your $HOME',
 'folder': '',
 'full_script': '/tmp/robotlab-2019.12.0/lib/python3.6/site-packages/robotlab/launch.py',
 'icon': '/tmp/robotlab-2019.12.0/lib/python3.6/site-packages/robotlab/icons/lab.ico',
 'name': 'RobotLab',
 'script': '/tmp/robotlab-2019.12.0/lib/python3.6/site-packages/robotlab/launch.py',
 'target': '~/Desktop/RobotLab.desktop'}
installation finished.

```

**Comment by datakurre** [comment]
@bollwyvl Then it was just me. I will check the hash.

Maybe this means that 2019.12.0 is finally ready 😅

**Comment by datakurre** [comment]
@bollwyvl Confirmed that my Linux-issue was my own mistake. Sorry for the false flag, but thanks for testing!

I will release 2019.12.0 :tada: :rocket:

**Comment by bollwyvl** [comment]
Yay!

**Pull request merged**
