### PR TITLE
robotframework-seleniumlibrary: 4.0.0 -> 4.1.0

### PR DESCRIPTION
**Pull request by datakurre**
seleniumlibrary 4.0.0 has some kind of new plugin architecture that allows experiments as separate plugings. seleniumtestability is a such plugin that add implicit wait for testing JavaScript-application based on some new webdriver support

### CODE REVIEW

**Comment by datakurre** [comment]
That said, something in that breaks seleniumscreenshots-package, so need to fix it into this

**Comment by bollwyvl** [comment]
Cool!

I've been running into some issues with rfst, so haven't been key to jump
on it all the way, will be interested to see what we come up with here...

**Comment by datakurre** [comment]
@bollwyvl What kind of issues have you had with rfst? I actually failed to find any issues with seleniumscreenshots, so my issues were probably caused by rfst.

**Comment by bollwyvl** [comment]
Iframe stuff mostly... Doesn't always install itself. We wrote a "select
and instrument frame" and have been mostly okay.

**Comment by datakurre** [comment]
Ok. I'm getting a quit a lot of "Timed out waiting for testability ready callback to trigger" exceptions from rfst and while I've found workarounds, I've not figured out what is the root cause for them.

That said, SeleniumScreenshots was not the issue after, so I'd like to merge SeleniumTestability into RobotLab even it is still in its early stages.

But I'm not in hurry. I want to make a few small fixes into robotkernel before the "November release".

**Comment by bollwyvl** [comment]
BAM!

**Pull request merged**
